### ISSUE TITLE
Add FAQ page

### ISSUE THREAD

**Issue by ghu7994** [doc19org/medicam#24]
Add a page with frequently asked questions about Coronavirus. This will also be good for SEO.

Examples of good existing resources:
- https://www.getroman.com/health-guide/coronavirus/
- https://www.cdc.gov/coronavirus/2019-ncov/faq.html
- https://www.mayoclinic.org/diseases-conditions/coronavirus/expert-answers/novel-coronavirus/faq-20478727
- https://www.pbs.org/newshour/health/the-essential-coronavirus-faq

**Comment by bryanaka** [comment]
addressing in https://github.com/doc19org/medicam/pull/32/
