### ISSUE TITLE
Extend FAQ page

### ISSUE THREAD

**Issue by ghu7994** [doc19org/medicam#41]
Add more content to the FAQ page. These are some good existing resources:

- https://www.getroman.com/health-guide/coronavirus/
- https://www.cdc.gov/coronavirus/2019-ncov/faq.html
- https://www.mayoclinic.org/diseases-conditions/coronavirus/expert-answers/novel-coronavirus/faq-20478727
- https://www.pbs.org/newshour/health/the-essential-coronavirus-faq

**Comment by IjeomaOdoko** [comment]
Hello would like to help with this. Do I just draft something on a Word Document or do I need to write it using HTML Code? 
Totally new at this.

**Comment by ghu7994** [comment]
Hi @IjeomaOdoko, you can use Word and attach it here, and I'll convert to HTML.
Our existing content is here: https://doc19.org/clinic/faq/

**Comment by IjeomaOdoko** [comment]
I will work on this. Not sure how to assign this task to myself.

**Comment by IjeomaOdoko** [comment]
[Frequently Asked Questions (1).zip](https://github.com/doc19org/medicam/files/4391230/Frequently.Asked.Questions.1.zip)

Let me know if you cant view it and i need to resend it as Word document. Prepared it using google docs.

If you need me to add more information or make any changes please advise. Otherwise I will check back tomorrow for another task.

**Comment by ghu7994** [comment]
Thanks! I can view it. I'll add this content to the site tomorrow.

**Comment by ghu7994** [comment]
I got sidetracked today, will add this content over the weekend.

**Comment by IjeomaOdoko** [comment]
No worries, I will check by again on Monday so see what else I can help
with.

**Comment by ghu7994** [comment]
(note to self) merge with Vinh's doc: https://docs.google.com/document/d/1S0NpUTxWGYtNeNYMknb62V0lGww9zolsumr73Oxlo18/edit

**Comment by ghu7994** [comment]
Updated the FAQ page with content from these documents. Thanks!
