### ISSUE TITLE
Set cookies on the right domain

### ISSUE THREAD

**Issue by ghu7994** [doc19org/medicam#44]
Cookies should be set for the current site's domain, e.g. `doc19.org` vs `demo.platform.doc19.org`

**Comment by prayashm** [comment]
By default the cookies will be set against the domain, the page was served from [1].

[1] https://docs.djangoproject.com/en/3.0/ref/request-response/#django.http.HttpResponse.set_cookie

**Comment by ghu7994** [comment]
Ah, good call, thanks!

> Do we want the demo env's cookies to be accessible in doc19.org domain?

No, each domain should be isolated from the others.

Closing this.
